Update CMake build
ARMmbed/mbed-os-example-sys-info pull request #79
Opened 2021-04-12 09:03 UTC by Patater

Update the example to work with the current Mbed OS CMake support.

2021-04-12 09:48 UTC, LDong-Arm commented
Looks like Travis is not using `.travis.yml` from this PR. It's worth checking the setting in https://travis-ci.com/github/ARMmbed/mbed-os-example-sys-info which I don't have permissions for.
@0xc0170 Are you able to help?

2021-04-12 09:50 UTC, LDong-Arm requested changes

2021-04-12 09:50 UTC, LDong-Arm commented on README.md
> +    * Mbed CLI 2
Please also update the first section above regarding Mbed CLI. We could use https://github.com/ARMmbed/mbed-os-example-blinky#mbed-os-build-tools as a template.

2021-04-12 13:12 UTC, LDong-Arm approved these changes
LGTM

2021-04-12 13:32 UTC, LDong-Arm requested changes

2021-04-12 13:32 UTC, LDong-Arm commented on README.md
> +Depending on the target, you can build the example project with the `GCC_ARM`, `ARM` or `IAR` toolchain. After installing Arm Mbed CLI, run the command below to determine which toolchain supports you
```suggestion
Depending on the target, you can build the example project with the `GCC_ARM` or `ARM` toolchain. After installing Arm Mbed CLI, run the command below to determine which toolchain supports your target:
```

2021-04-12 14:36 UTC, LDong-Arm approved these changes
LGTM

2021-04-13 08:54 UTC, 0xc0170 approved these changes

2021-04-13 08:55 UTC, merged